name: Lint

on: [push, pull_request, workflow_dispatch]

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0

      - name: Check spelling
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files --hook-stage manual codespell || true

      - name: Check spelling (action)
        uses: codespell-project/actions-codespell@v1
        with:
          only_warn: 1
